In [2]:
#NumPy Matrix Program

#step 1: Import NumPy
import numpy as np

In [7]:
#step 2: Create Matrices
A=np.array([[1, 2, 3],
           [4, 5, 6]])
B=np.array([[7, 8, 9],
            [1, 2, 3]])
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])
D = np.array([[1, 2],
              [3, 4]])

In [5]:
#Step 3: Display Matrices
print("----Display Matrices----")
print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Matrix C:\n",C)
print("Matrix D:\n",D)

----Display Matrices----
Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[7 8 9]
 [1 2 3]]
Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Matrix D:
 [[1 2]
 [3 4]]


In [10]:
#Step 4: Matrix Properties
print("----Matrix Properties----\n")
print("Shape: ",A.shape)
print("Dimension: ",A.ndim)
print("Size: ",A.size)

----Matrix Properties----

Shape:  (2, 3)
Dimension:  2
Size:  6


In [12]:
#Step 5: Access Elements
print("----Access Elements----\n")
print("A[0,1]:", A[0,1])
print("A[1,2]:", A[1,2])

----Access Elements----

A[0,1]: 2
A[1,2]: 6


In [11]:
#Step 6: Basic Operations
print("A+B:\n",A+B)
print("A-B:\n",A-B)
print("A*2:\n",A*2)

A+B:
 [[ 8 10 12]
 [ 5  7  9]]
A-B:
 [[-6 -6 -6]
 [ 3  3  3]]
A*2:
 [[ 2  4  6]
 [ 8 10 12]]


In [20]:
#Step 7: Matrix Multiplication
print("----Matrix Multiplication----")
print("C@A:\n",C @ A)

----Matrix Multiplication----
C@A:
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [24]:
#Step 8: Transpose
print("----Transpose of A----")
print(A.T)

----Transpose of A----
[[1 4]
 [2 5]
 [3 6]]


In [23]:
# Step 9: Special Matrices
print("----Special Matrices----")
print("Zero Matrix:\n",np.zeros((2,3)))
print("One Matrix:\n",np.ones((2,3)))
print("Identity Matrix:\n",np.eye(4))

----Special Matrices----
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
One Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
